config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  authenticated :user do
    root to: 'groups#index', as: :authenticated_root
  end
  root to: 'groups#index'

  resources :users do
    resources :groups do
      resources :wallets
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_many :groups, through: :group_entities
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_wallets, dependent: :destroy
  has_many :wallets, through: :group_wallets

  validates :name, presence: true
  validates :icon, presence: true

  has_one_attached :icon
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/group_wallet.rb
class GroupWallet < ApplicationRecord
  belongs_to :group
  belongs_to :wallet
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable, :confirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :wallets, dependent: :destroy

  validates :name, presence: true
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  has_many :group_wallets, dependent: :destroy
  has_many :groups, through: :group_wallets

  validates :name, presence: true
  validates :amount, presence: true, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @items = current_user.groups.includes(:wallets)
    @total_amount = 0
    @items.each do |item|
      @total_amount += item.wallets.sum(:amount)
    end
  end

  def show
    @current_user = current_user
    @group = @current_user.groups.find(params[:id])
    @wallets = @group.wallets
  end

  def new
    @current_user = current_user
    @group = Group.new
  end

  def create
    @create_group = current_user.groups.build(group_params)
    if @create_group.save
      flash[:notice] = 'Successful Added'
      redirect_to user_groups_path(current_user)
    else
      flash[:alert] = 'failed to Add'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
  end

  def show; end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :authenticate_user!
  def show
    @current_user = current_user
    @group = @current_user.groups.find(params[:group_id])
    @wallets = @group.wallets
    @wallet = @wallets.find(params[:id])
  end

  def new
    @current_user = current_user
    @groups = @current_user.groups
    @group = @current_user.groups.find_by_id(params[:group_id])
    @wallet = @group.wallets.new
  end

  def create
    @current_user = current_user
    @wallet_create = @current_user.wallets.build(wallet_params)
    if @wallet_create.save
      @group_wallets = GroupWallet.create(group_id: params[:groups], wallet_id: @wallet_create.id)
      redirect_to "/users/#{current_user.id}/groups/"

      flash[:notice] = 'successful created'
    else
      flash[:alert] = 'Something Wrong'
    end
  end

  private

  def wallet_params
    params.require(:wallet).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/groups/index.html.erb
<section class="home">
<%= render partial: 'share/nav', locals: { back: "Home", back_path: root_path } %>
<div class="container-fluid bg-white d-flex flex-row justify-content-between align-items-center p-1">
<h4>Total Budget:</h4>
<h4><b><%= @total_amount %></b> $</h4>
</div>
<div class="group px-5 d-flex align-items-center flex-column">
<h1 class="custom_color">Your Catogeries</h1>
<div class="card w-100">
<ul class="card list-group">
<% @items.each do |item| %>
    <li class="px-2 list-group-item d-flex justify-content-between align-items-center col-12"> 
    <div class=" d-flex justify-content-between align-items-center col-8">
    <div class="d-flex align-items-center gap-1">
    <% if item.icon.attached? %>
    <%= image_tag item.icon, class: "img-item" %> 
    <% end %>
    <h5><%= link_to item.name, user_group_path(current_user,id: item.id), class: "text-decoration-none text-primary" %></h5>
    </div></div> <div class="d-flex flex-column col-2"><span class="fs-2">
    <%= item.wallets.map { |item| item.amount }.sum %> $
  </span>
     <span class="text-primary date"><b class="text-dark px-2">Date: </b><%= item.created_at.strftime('%B-%d-%Y') %></span>
     </div></li>
    <% end %>
</ul>
</div>
</div>
<div class="button"><%= render partial: 'share/button', locals: {button_text:"Add a New Category", button_path:new_user_group_path(current_user)} %></div>
</section>

app/views/groups/new.html.erb
<section class="group_form d-flex flex-column justify-content-center align-items-center">
<h1 class="text-dark">Add new Catogery</h1>
<%= render partial: 'share/group' %>
</section>

app/views/groups/show.html.erb
<div>
<%= render partial: 'share/nav', locals: { back: "Go back", back_path: root_path } %>
<div class='top d-flex flex-row align-items-center justify-content-between p-2'>
<h1 class="text-center text-dark"><%= image_tag @group.icon, class: "small-icon" %><%= @group.name %></h1>
<h2>
<%= @wallets.map { |item| item.amount }.sum %> $
</h2>
</div>
<div class="items-container p-2">
<ul class="card list-group">
<% @wallets.each do |wallet| %>
<li class="list-group-item d-flex flex-row justify-content-between align-items-center">
<div class="fs-4">
<%= link_to wallet.name, user_group_wallet_path(current_user, @group, wallet.id), class: "text-decoration-none text-primary" %>
</div>
<div class="d-flex flex-column align-items-center">
<h4 class="fs-4"><%= wallet.amount %> $</h4>
<span class="text-primary"><b class="text-dark px-2">Date: </b><%= wallet.created_at.strftime('%B-%d-%Y') %></span>
</div>
</li>
<% end %>
</ul>
</div>
<div class="button"><%= render partial: 'share/button', locals: {button_text:"Add New Transaction", button_path:new_user_group_wallet_path(current_user, @group)} %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: '/share/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/share/_button.html.erb
<%= link_to button_text, button_path, class: 'btn col-12' %>

app/views/share/_group.html.erb
<%= form_with model: [current_user, @group] do |form| %>

    <div class="card p-3">

    <div class="field mb-3 d-flex flex-column justify-content-center">
    <%= form.label :name %>
    <%= form.text_field :name %><br>
    <div>

    <div class="field mb-3 d-flex flex-column justify-content-center">
    <%= form.label :icon %>
    <%= form.file_field :icon %><br>
    </div>

    <div class="mb-3">
    <%= form.submit "Submit" %>
    </div>
    </div>

    <% end %>

app/views/share/_nav.html.erb
<nav class="navs d-flex flex-row justify-content-between text-light align-items-center px-2">
<%= link_to back, back_path, class: "text-light text-decoration-none fs-3" %>
<span class="fs-4">Smart Wallet</span>
</nav>

app/views/share/_navbar.html.erb
<div class="collapse" id="navbarToggleExternalContent" data-bs-theme="secondary">
  <div class="menu p-4 d-flex flex-row justify-content-between">
    <h5 class="text-light">Smart Wallet APP</h5>
    <h5 class="text-primary">
    <% if user_signed_in? %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>
<div class="d-flex flex-row gap-3">
<%= link_to 'Sign in', new_user_session_path, style: "text-decoration:none;" %>
</div>
<% end %>
    </h5>
  </div>
</div>
<nav class="navbar navbar-dark menu">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex flex-row align-items-center align-items-center gap-2 text-light notifaction">
    <%= render partial: '/share/notification' %>
    <span class="text-light"><i class="fa-solid fa-magnifying-glass"></i></span>
    </div>
  </div>
</nav>

app/views/share/_notification.html.erb
<div class="d-flex flex-row justify-content-center align-items-center">
<span class="notice"><%= notice %></span>
<span class="alert"><%= alert %></span>
</div>

app/views/share/_wallet.html.erb
<%= form_with url: user_group_wallets_path, method: :post do |form| %>
    <div class="card p-3">
      <div class="field mb-3 d-flex flex-column justify-content-center">
        <%= form.label :name %>
        <%= form.text_field :name, name: 'wallet[name]' %>
      </div>
  
      <div class="field mb-3 d-flex flex-column justify-content-center">
        <%= form.label :amount %>
        <%= form.text_field :amount, name: 'wallet[amount]' %>
      </div>

      <div class="field mb-3 d-flex flex-column justify-content-center">
      <%= form.label :groups %>
      <%= form.select :groups, options_from_collection_for_select(@groups, 'id', 'name') %>
    </div>
  
      <div class="mb-3">
        <%= form.submit "Submit" %>
      </div>
    </div>
  <% end %>
  

app/views/users/show.html.erb
<h1>Good Bye</h1>

app/views/wallets/new.html.erb
<%= render partial: 'share/wallet' %>

app/views/wallets/show.html.erb
<section class="d-flex flex-column pb-2 item-show">
<%= render partial: 'share/nav', locals: { back: "Go back", back_path: user_group_path(current_user, @group) } %>
<div class="d-flex flex-row justify-content-between align-items-center p-2">
<h1 class="">Name: <%= @wallet.name %></h1>
<h4 class="">Catogery: <%= @group.name %></h4>
</div>
<div class="item-image d-flex flex-column align-items-center justify-content-center">
<%= image_tag @group.icon, class: "img-fluid img-thumbnail" %>
<h4 class="pt-2 text-dark fs-3">Amount: <%=@wallet.amount %>$</h4>
<span class="text-primary date pt-4"><b class="text-dark px-2">Date: </b><%= @wallet.created_at.strftime('%B-%d-%Y') %></span>
</div>
</section>